# Generated by Django 3.0.5 on 2020-12-15 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateId',
            fields=[
                ('ID', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('message', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'templateid',
            },
        ),
    ]
